#!/usr/bin/env python3
"""Draw `public/item-hair-effigy.png` — the relic Black Annis leaves behind.

A 32x32 bag icon, same size as `item-blood-cap.png` and `item-grave-helm.png`.
Drawn rather than sourced, so it carries no third-party licence at all and can
be regenerated byte-identically from this file: `python3 tools/gen_hair_effigy.py`.

WHAT IT IS. A crude poppet bound out of plaited black hair over a stick cross,
with two twists of pale hide for a face and a rag of skirt. Not a doll anyone
made with care — a decoy meant to be seen from below, at night, in a tree.

The palette is the mission's: her hair-black and the rust of the leathers she
wears, with the one cold note reserved for the face, which is the only part of
her the county ever claimed to see clearly.

    run from the repo root; writes into public/
"""
from PIL import Image, ImageDraw

HAIR = (24, 22, 26, 255)        # her hair, near-black with a blue cast
HAIR_HI = (52, 48, 58, 255)     # the sheen that says "plaited", not "blob"
BIND = (122, 74, 38, 255)       # rust leather cord, the clothes she wears
BIND_HI = (162, 104, 56, 255)
HIDE = (176, 168, 150, 255)     # pale tanned skin, the face
HIDE_SH = (132, 124, 110, 255)
STICK = (86, 72, 56, 255)       # the cross underneath, showing at the ends

im = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
d = ImageDraw.Draw(im)

# The stick cross, showing only where the binding runs out.
d.line([(16, 6), (16, 27)], fill=STICK, width=2)
d.line([(7, 13), (25, 13)], fill=STICK, width=2)

# Arms: hair wound out along the cross-piece, thinning toward the tips.
d.line([(9, 13), (23, 13)], fill=HAIR, width=3)
d.line([(10, 12), (22, 12)], fill=HAIR_HI, width=1)
d.line([(8, 13), (9, 13)], fill=BIND, width=2)
d.line([(23, 13), (24, 13)], fill=BIND, width=2)

# Body: a bound bundle, widest at the waist where the skirt-rag hangs.
d.polygon([(13, 15), (19, 15), (21, 25), (11, 25)], fill=HAIR)
d.polygon([(14, 16), (18, 16), (19, 21), (13, 21)], fill=HAIR_HI)
# Three cords across it. This is the part that reads as "made", not "grown".
for y in (17, 20, 23):
    d.line([(12, y), (20, y)], fill=BIND, width=1)
d.line([(12, 20), (20, 20)], fill=BIND_HI, width=1)

# Skirt-rag, torn off square at the bottom.
d.polygon([(11, 25), (21, 25), (22, 28), (10, 28)], fill=BIND)
d.line([(10, 28), (22, 28)], fill=(92, 56, 28, 255), width=1)

# Head: two twists of hide, and the hair falling past it on both sides —
# which on the real thing is the whole trick, because hair is all you see
# of her from the ground.
d.ellipse([(12, 4), (20, 12)], fill=HIDE)
d.ellipse([(13, 5), (17, 9)], fill=(198, 190, 172, 255))
d.line([(12, 7), (12, 16)], fill=HAIR, width=2)
d.line([(20, 7), (20, 16)], fill=HAIR, width=2)
d.line([(11, 8), (11, 14)], fill=HAIR_HI, width=1)
d.line([(21, 8), (21, 14)], fill=HAIR_HI, width=1)
# No eyes. A face with eyes is a doll; a face without them is a decoy.
d.line([(14, 10), (18, 10)], fill=HIDE_SH, width=1)

im.save("public/item-hair-effigy.png")
print("wrote public/item-hair-effigy.png", im.size)
