#!/usr/bin/env python3
"""Draw `public/item-minotaur-earring.png` — the relic the Minotaur leaves.

A 32x32 bag icon, the same size as `item-hair-effigy.png` and the two relics
before it. Drawn rather than sourced, so it carries no third-party licence at
all and can be regenerated byte-identically from this file:

    python3 tools/gen_minotaur_earring.py     (run from the repo root)

WHAT IT IS. A heavy bronze hoop, pulled out of round, with a torn crescent of
fur-tan hide still hanging on it. Not jewellery a hero kept as a keepsake —
EVIDENCE, which is what every relic in this chain is. Chronos wants proof that
the thing in the labyrinth was WORN: a beast does not put a ring in its own
ear, and somebody did.

It is deliberately NOT another ring silhouette. The guard ring in the same
hoard is a fat three-quarter band filling the cell; this is a thin open hoop
tilted the other way with something hanging off it, so the two can never be
confused in a bag at twelve pixels.

The palette is the mission's bronze against the fur-tan of the sheet the boss
is cut from, with the one dark note reserved for the tear.

This is A PLACEHOLDER by agreement: Radek is replacing the artwork later.
"""
from PIL import Image, ImageDraw

HOOP = (168, 118, 46, 255)      # old bronze, warmer than the guard ring's iron
HOOP_HI = (232, 184, 100, 255)
HOOP_SH = (98, 66, 24, 255)
HIDE = (182, 138, 92, 255)      # fur-tan, the boss's own colour
HIDE_SH = (124, 88, 54, 255)
HIDE_HI = (214, 176, 130, 255)
TEAR = (98, 42, 38, 255)        # where it came away
NICK = (240, 214, 160, 255)     # a bright scratch on the metal

im = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
d = ImageDraw.Draw(im)

# The hide first, so the hoop draws over it and reads as threaded THROUGH
# rather than laid beside. A torn lobe, hanging from the top of the hoop:
# wide where the ear was, ragged along the edge that gave way.
d.polygon([(10, 2), (20, 3), (22, 10), (19, 15), (13, 13), (10, 7)], fill=HIDE)
d.polygon([(12, 4), (18, 5), (19, 9), (16, 12), (13, 10)], fill=HIDE_HI)
d.line([(10, 2), (10, 7)], fill=HIDE_SH, width=1)
d.line([(22, 10), (19, 15)], fill=HIDE_SH, width=1)
# The tear itself — the one dark run, along the bottom edge and up the side.
d.line([(13, 13), (19, 15)], fill=TEAR, width=1)
d.line([(10, 7), (13, 13)], fill=TEAR, width=1)
d.line([(10, 2), (20, 3)], fill=TEAR, width=1)

# The hoop. Thin metal, open, and pulled out of round — wider across than tall,
# which is what says "this came out of an ear by force" rather than "bought".
d.ellipse([(5, 12), (29, 30)], outline=HOOP, width=3)
d.arc([(5, 12), (29, 30)], start=140, end=250, fill=HOOP_HI, width=2)
d.arc([(5, 12), (29, 30)], start=330, end=45, fill=HOOP_SH, width=2)
# The kink where it was dragged straight, top left.
d.line([(7, 16), (14, 12)], fill=HOOP, width=3)
d.line([(7, 15), (14, 11)], fill=HOOP_HI, width=1)
d.point((11, 13), fill=NICK)
# The gap: a hoop that has been forced open does not close again.
d.line([(20, 12), (24, 14)], fill=(0, 0, 0, 0), width=3)

im.save("public/item-minotaur-earring.png")
print("wrote public/item-minotaur-earring.png")
