#!/usr/bin/env python3
"""Draw `public/item-guard-ring.png` — the ring buried in the Minotaur's hoard.

A 32x32 bag icon, the same size as every other item in the game. Drawn rather
than sourced, so it carries no third-party licence at all and can be
regenerated byte-identically from this file:

    python3 tools/gen_guard_ring.py        (run from the repo root)

WHAT IT IS. The Power Ring's opposite number, and drawn to be READ as that:
the same three-quarter view and the same weight in the cell, so the two sit
side by side in a bag and are obviously one pair. What differs is the metal
and the front — where the Power Ring is a light gold band with a green stone
cut for show, this is dark iron banded in bronze with a flat plate riveted
across it. A knuckle-guard, not a jewel. The stone is a cold grey-blue set
FLUSH into the plate rather than raised out of it, because anything standing
proud of the band would catch on a shield strap.

This is A PLACEHOLDER by agreement: Radek is replacing the artwork later. It
exists so the item can ship, be looted, be worn and be tested today instead of
showing a baked blob in the bag.
"""
from PIL import Image, ImageDraw

IRON = (74, 78, 88, 255)        # the band: dark iron, cold against the bronze
IRON_HI = (128, 134, 148, 255)
IRON_SH = (44, 46, 54, 255)
BRONZE = (154, 108, 52, 255)    # the two collars binding the band
BRONZE_HI = (208, 158, 92, 255)
PLATE = (110, 116, 128, 255)    # the riveted face
PLATE_HI = (176, 184, 198, 255)
PLATE_SH = (58, 62, 72, 255)
STONE = (74, 108, 146, 255)     # cold grey-blue, set flush
STONE_HI = (152, 190, 218, 255)
HOLE = (0, 0, 0, 0)             # what you see through it: the bag behind

im = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
d = ImageDraw.Draw(im)

# The band, three-quarter on and filling the cell the way the Power Ring does.
# Outer, then the lit rim, then the shaded inner wall, then the hole through.
d.ellipse([(3, 7), (29, 29)], fill=IRON)
d.ellipse([(4, 8), (28, 27)], fill=IRON_HI)
d.ellipse([(6, 10), (26, 27)], fill=IRON)
d.ellipse([(9, 14), (23, 25)], fill=IRON_SH)
d.ellipse([(10, 15), (22, 24)], fill=HOLE)

# Two bronze collars around the band, left and right of the plate. They are
# what stops the thing reading as a plain grey doughnut.
d.arc([(3, 7), (29, 29)], start=118, end=172, fill=BRONZE, width=4)
d.arc([(3, 7), (29, 29)], start=8, end=62, fill=BRONZE, width=4)
d.arc([(4, 8), (28, 28)], start=124, end=166, fill=BRONZE_HI, width=1)

# The guard plate across the front, where a knuckle goes.
d.polygon([(9, 11), (23, 11), (21, 3), (11, 3)], fill=PLATE)
d.polygon([(11, 10), (21, 10), (19, 4), (13, 4)], fill=PLATE_HI)
d.line([(9, 11), (23, 11)], fill=PLATE_SH, width=1)
d.line([(11, 3), (21, 3)], fill=PLATE_SH, width=1)

# The stone, flush into the plate.
d.ellipse([(13, 4), (19, 9)], fill=STONE)
d.ellipse([(14, 5), (16, 7)], fill=STONE_HI)

# Four rivets, one at each corner of the plate.
for px, py in ((10, 10), (22, 10), (12, 4), (20, 4)):
    d.point((px, py), fill=BRONZE_HI)

im.save("public/item-guard-ring.png")
print("wrote public/item-guard-ring.png")
